### ISSUE TITLE
Staging2: 500 error when adding a conditional container in a container widget

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#109]
**Describe the bug**

<img width="780" alt="5002" src="https://user-images.githubusercontent.com/67583075/210510714-5ddf171a-2415-4d4c-b643-06fe473d7754.png">

**Comment by wongpratan** [comment]
It happens often in staging2 site.

aBUa6HU7c::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
_AZoaT4nb::"PUT /definition/bfbc40b6-18b9-4ffd-bef9-b7b349a3bc16"
_AZoaT4nb::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
Cx2BpmsT97::"PUT /definition/23de8b84-cf92-4bdd-b809-8fab1c33c4b1"
Cx2BpmsT97::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
B5vHMgZe64::"PUT /definition/e3947f2d-27aa-43c1-8aca-fb4f8b889f6d"
B5vHMgZe64::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
fO_04LBk3Z::"PUT /definition/630f64aa-b976-41b8-af3c-7a61d934ab27"
fO_04LBk3Z::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
TXDjI0Bgjf::"PUT /definition/f24f0818-630e-4aef-8004-afce089bb35c"
TXDjI0Bgjf::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
f-RNexyD2I::"PUT /definition/24a7e7cf-43cd-48ec-855b-5eef352c37c2"
f-RNexyD2I::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
MktjV-ogzJ::"PUT /definition/997a106f-2e07-4bb1-8c01-db419fc651f3"
MktjV-ogzJ::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
9xoI-B3bZY::"PUT /definition/92974e84-f463-4a4e-aed0-a02475ed1e61"
9xoI-B3bZY::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
l15RXoZxVM::"PUT /definition/0f2c6fe4-5a6b-4441-8bb1-fa7b3028c059"
l15RXoZxVM::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
Nq18qpQcIS::"PUT /definition/c557b0e1-5003-4803-a3df-8538eb894cbe"
Nq18qpQcIS::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
4xQwNgLwU-::"PUT /definition/69a16c83-64e4-4c3c-8a3e-ea01da5ad00d"
4xQwNgLwU-::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
xKGKrDyioM::"PUT /definition/b8919b57-83e2-4c8b-adbb-831a70a11caf"
xKGKrDyioM::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
_AZoaT4nb::"authUser -> session"
Cx2BpmsT97::"authUser -> session"
B5vHMgZe64::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
fO_04LBk3Z::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TXDjI0Bgjf::"authUser -> session"
f-RNexyD2I::"authUser -> session"
MktjV-ogzJ::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
9xoI-B3bZY::"authUser -> session"
l15RXoZxVM::"authUser -> session"
Nq18qpQcIS::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
4xQwNgLwU-::"authUser -> session"
xKGKrDyioM::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
GJ5YW4zsg::"GET /app_builder/model/2a662d46-384b-4d3b-901b-b74c0cd39b15"
GJ5YW4zsg::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
y_jBdnAyct::"GET /app_builder/model/c3aae079-d36d-489f-ae1e-a6289536cb1a"
y_jBdnAyct::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
SIeZuX72xQ::"PUT /definition/85889ed0-970c-4fd5-8bb8-e512f8b95e4c"
SIeZuX72xQ::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
y_jBdnAyct::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
GJ5YW4zsg::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
SIeZuX72xQ::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
a48wHG3RA::"PUT /definition/c258deb6-bf19-414f-9941-8de609a088f6"
a48wHG3RA::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
a48wHG3RA::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
xbkOqlo1I::"GET /app_builder/model/2a662d46-384b-4d3b-901b-b74c0cd39b15"
xbkOqlo1I::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
a77u2KSpoI::"GET /app_builder/model/c3aae079-d36d-489f-ae1e-a6289536cb1a"
a77u2KSpoI::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
xbkOqlo1I::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
a77u2KSpoI::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
LOyQ3Nd8M::"GET /app_builder/model/2a662d46-384b-4d3b-901b-b74c0cd39b15"
LOyQ3Nd8M::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
yybzjeF5et::"GET /app_builder/model/c3aae079-d36d-489f-ae1e-a6289536cb1a"
yybzjeF5et::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
CH1PHdVfh5::"PUT /definition/c258deb6-bf19-414f-9941-8de609a088f6"
CH1PHdVfh5::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
LOyQ3Nd8M::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
yybzjeF5et::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CH1PHdVfh5::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleUnmatchedNext (/app/node_modules/sails/lib/router/index.js:250:21)
    at /app/node_modules/router/index.js:676:15
    at next (/app/node_modules/router/index.js:275:14)
    at next (/app/node_modules/router/lib/route.js:124:14)
    at /app/api/policies/authUser.js:168:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JM_uff2fr::"GET /config"
JM_uff2fr::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
JM_uff2fr::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleError (/app/node_modules/sails/lib/hooks/http/initialize.js:427:19)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
Rk3p7ymLE::"GET /"
Rk3p7ymLE::"authTenant -> session"
authUser::"performance.mark() is overwriting existing key [user_manager.user-find]"
Rk3p7ymLE::"authUser -> session"
error: Sending 500 ("Server Error") response: 
 Error: TypeError: Cannot read property 'length' of undefined
    at flaverr (/app/node_modules/flaverr/index.js:94:15)
    at Function.module.exports.parseError (/app/node_modules/flaverr/index.js:371:12)
    at Object.serverError (/app/node_modules/sails/lib/hooks/responses/defaults/serverError.js:35:74)
    at Sails.500 (/app/node_modules/sails/lib/router/bindDefaultHandlers.js:55:22)
    at Sails.emit (node:events:394:28)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:56:26)
    at handleError (/app/node_modules/sails/lib/hooks/http/initialize.js:427:19)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)

**Comment by wei9528** [comment]
@Hiro-Nakamura Hi Johnny, should be stable to reproduce when you add another conditional container under an IF container.

**Comment by Hiro-Nakamura** [comment]
I'm having a hard time recreating this error.  

@wongpratan If you are able to reproduce this again, can you try to monitor the system logs and give me a dump of those:
```
$ ./pod-logs.sh system
```

That might reveal more info about where that error is actually being generated.

**Comment by wongpratan** [comment]
This runtime error was solved in [this code](https://github.com/Vincit/db-errors/blob/master/lib/parsers/mysql/DBError/parser.js#L11) that updated 2 years ago.

But latest [db-errors](https://www.npmjs.com/package/db-errors/v/0.2.3?activeTab=explore) library was published 4 years ago.

`/db-errors/lib/parsers/mysql/DBError/parser.js`

```
  parse: (err) => {
    if (typeof err.code === 'string'
      && 'sqlMessage' in err
      && 'sqlState' in err
      && err.sqlState.length === 5
      && errorCodes.has(err.code)
      && typeof err.errno === 'number') {

      return {
        nativeError: err,
        client: 'mysql'
      };
    }

    return null;
  },
  ```
  (`db-errors` is included in [objection](https://www.npmjs.com/package/objection/v/2.2.18?activeTab=dependencies) library)

**Comment by Hiro-Nakamura** [comment]
So is the `try{}catch(){}` properly handling that error now?

**Comment by Hiro-Nakamura** [comment]
Would upgrading `objection` to v3.0.1 have the updated `db-errors` library?

**Comment by wongpratan** [comment]
> So is the `try{}catch(){}` properly handling that error now?
It helps to prevent the runtime break in the service.

> Would upgrading `objection` to v3.0.1 have the updated `db-errors` library?
`objection` v3.0.1 still uses the same `db-errors` version (latest)
https://www.npmjs.com/package/db-errors?activeTab=versions

**Comment by Hiro-Nakamura** [comment]
how did you patch the `db-errors` and get it into the Docker container?
