### ISSUE TITLE
Site User Object of AB Designer's Site Administration on Childatrisk Servers make server get down.

### ISSUE THREAD

**Issue by Tacchinardi20** [digi-serve/plugin_ABDesigner#231]
When we go to AB Designer's Site Administration of any Childatrisk Servers, then click on site user object and make something change on the grid. The server will get down for a while and restart itself every time that we made a change.

Like In this picture, I had clicked on Add New Role Button.

![image](https://github.com/digi-serve/plugin_ABDesigner/assets/98794744/4033d72a-60e4-49f2-9e15-c070728af075)

**Comment by wongpratan** [comment]
```
cars_api_sails          :  TypeError: Cannot convert undefined or null to object
cars_api_sails          :      at ABServiceResponder.handler (/app/api/lib/cacheManager.js:44:51)
cars_api_sails          :      at /app/node_modules/@digiserve/ab-utils/utils/reqServiceResponder.js:63:15
cars_api_sails          :      at Responder.<anonymous> (/app/node_modules/cote/src/components/responder.js:48:24)
cars_api_sails          :      at EventEmitter.emit (/app/node_modules/eventemitter2/lib/eventemitter2.js:390:22)
cars_api_sails          :      at RepSocket.<anonymous> (/app/node_modules/cote/src/components/responder.js:23:18)
cars_api_sails          :      at RepSocket.emit (node:events:513:28)
cars_api_sails          :      at RepSocket.emit (node:domain:489:12)
cars_api_sails          :      at Parser.<anonymous> (/app/node_modules/@dashersw/axon/lib/sockets/rep.js:51:15)
cars_api_sails          :      at Parser.emit (node:events:513:28)
cars_api_sails          :      at Parser.emit (node:domain:489:12)
cars_api_sails          :      at Parser._write (/app/node_modules/amp/lib/stream.js:91:16)
cars_api_sails          :      at writeOrBuffer (node:internal/streams/writable:392:12)
cars_api_sails          :      at _write (node:internal/streams/writable:333:10)
cars_api_sails          :      at Writable.write (node:internal/streams/writable:337:10)
cars_api_sails          :      at Socket.ondata (node:internal/streams/readable:766:22)
cars_api_sails          :      at Socket.emit (node:events:513:28)
cars_api_sails          :      at Socket.emit (node:domain:489:12)
cars_api_sails          :      at addChunk (node:internal/streams/readable:324:12)
cars_api_sails          :      at readableAddChunk (node:internal/streams/readable:297:9)
cars_api_sails          :      at Readable.push (node:internal/streams/readable:234:10)
cars_api_sails          :      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
cars_api_sails          :      at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```
